"""Canonical install bundles for the TIBET umbrella package.

This file is the single package-level map used by the sandbox proposal for
``pip install tibet[full]`` and the CLI status/doctor commands.
"""

PACKAGE_SPECS = {
    "tibet-core": "tibet-core>=0.5.0",
    "jis-core": "jis-core>=0.4.0",
    "tibet-audit": "tibet-audit>=0.27.1",
    "tibet-continuityd": "tibet-continuityd>=0.6.17",
    "tibet-cbom": "tibet-cbom>=0.2.2",
    "tibet-sbom": "tibet-sbom>=0.2.1",
    "tibet-ai-sbom": "tibet-ai-sbom>=0.2.3",
    "tibet-wayback": "tibet-wayback>=0.2.1",
    "tibet-nis2": "tibet-nis2>=0.1.1",
    "tibet-report": "tibet-report>=0.1.2",
    "tibet-trail": "tibet-trail>=0.1.1",
    "tibet-ci": "tibet-ci>=0.2.1",
    "ainternet": "ainternet>=0.9.2",
    "ipoll": "ipoll>=0.2.6",
    "tibet-ainternet-mcp": "tibet-ainternet-mcp>=0.5.7",
    "tibet-ipoll-mcp": "tibet-ipoll-mcp>=0.1.0",
    "tibet-triage": "tibet-triage>=0.5.2",
    "tibet-airlock": "tibet-airlock>=0.3.1",
    "tibet-phantom": "tibet-phantom>=0.2.2",
    "tibet-phantom-mcp": "tibet-phantom-mcp>=0.1.1",
    "tibet-cap-bus": "tibet-cap-bus>=0.1.4",
    "tibet-context": "tibet-context>=0.2.2",
    "tibet-cortex": "tibet-cortex>=0.2.1",
    "tibet-sam": "tibet-sam>=0.1.0",
    "tibet-router": "tibet-router>=0.1.2",
    "tibet-cobol": "tibet-cobol>=0.1.1",
    "snaft": "snaft>=1.4.1",
    "tibet-snaft": "tibet-snaft>=1.4.1",
    "inject-bender": "inject-bender>=0.3.1",
    "tibet-chip": "tibet-chip>=1.0.1",
    "tibet-claw": "tibet-claw>=0.3.2",
    "tibet-gateway": "tibet-gateway>=0.4.0",
    "tibet-home-agent": "tibet-home-agent>=0.5.3",
    "tibet-pol": "tibet-pol>=0.3.4",
    "tibet-ping": "tibet-ping>=0.3.4",
    "tibet-mux": "tibet-mux>=1.0.2",
    "tibet-overlay": "tibet-overlay>=0.1.2",
    "tibet-iot": "tibet-iot>=0.1.1",
    "tibet-edge": "tibet-edge>=0.1.1",
    "tibet-mesh": "tibet-mesh>=0.1.0",
    "tibet-zip": "tibet-zip>=1.1.1",
    "tibet-spiffe": "tibet-spiffe>=0.1.1",
    "tibet-tools": "tibet-tools>=0.1.1",
    "tibet-marketplace": "tibet-marketplace>=0.1.1",
    "tibet-nc": "tibet-nc>=0.1.2",
    "tibet-keychain": "tibet-keychain>=0.1.2",
    "tibet-tail": "tibet-tail>=0.2.1",
    "tibet-cascade": "tibet-cascade>=0.1.0",
    "tibet-soc": "tibet-soc>=0.1.1",
    "tibet-workload": "tibet-workload>=0.1.0",
    "tibet-conformance-vectors": "tibet-conformance-vectors>=0.2.2",
    "tibet-forge": "tibet-forge>=0.7.1",
    "tibet-vault": "tibet-vault>=0.1.0",
    "tibet-pqc": "tibet-pqc>=0.1.1",
    "tibet-anticheat": "tibet-anticheat>=0.1.2",
    "tibet-y2k38": "tibet-y2k38>=0.1.2",
    "tibet-timevector": "tibet-timevector>=0.1.0",
    "tibet-pol-mcp": "tibet-pol-mcp>=0.1.0",
    "tibet-triage-mcp": "tibet-triage-mcp>=0.1.0",
    "tibet-cmail": "tibet-cmail>=0.3.0",
    "tibet-genesis": "tibet-genesis>=0.1.4",
    "tibet-snap": "tibet-snap>=0.1.3",
}

PACKAGE_IMPORTS = {
    name: name.replace("-", "_")
    for name in PACKAGE_SPECS
}
PACKAGE_IMPORTS.update({
    "jis-core": "jis_core",
})

LEGACY_PACKAGES = {
    "tibet-snap": "Replaced by continuityd/wayback/phantom resume flows.",
    "tibet-cobol": "Niche legacy/enterprise adapter; opt-in only.",
    "tibet-y2k38": "Deprecated time bridge; opt-in only.",
    "tibet-anticheat": "Deprecated game-specific provenance demo; opt-in only.",
    "tibet-router": "Deprecated alias for tibet-llm-router.",
    "tibet-iot": "Deprecated alias merged into tibet-ping.",
}

BUNDLES = {
    "zero-state": {
        "desc": "T-1 bootstrap: identity, provenance, genesis and causal time",
        "packages": ["tibet-core", "jis-core", "tibet-genesis", "tibet-timevector"],
        "install": 'pip install "tibet[zero-state]"',
    },
    "continuity": {
        "desc": "Continuity, state resume, fork, replay and causal handoff",
        "packages": [
            "tibet-continuityd",
            "tibet-cap-bus",
            "tibet-cbom",
            "tibet-trail",
            "tibet-wayback",
            "tibet-phantom",
            "tibet-phantom-mcp",
        ],
        "install": 'pip install "tibet[continuity]"',
    },
    "network": {
        "desc": "Network primitives: ping, overlay, mux, nc, mesh and transfer",
        "packages": [
            "tibet-ping",
            "tibet-overlay",
            "tibet-mux",
            "tibet-nc",
            "tibet-mesh",
            "tibet-zip",
        ],
        "install": 'pip install "tibet[network]"',
    },
    "operator": {
        "desc": "Human/operator surface",
        "packages": ["tibet-pol", "tibet-tail", "tibet-cmail", "tibet-keychain", "tibet-home-agent"],
        "install": 'pip install "tibet[operator]"',
    },
    "observability": {
        "desc": "Cascade logging and causal observability across the stack",
        "packages": ["tibet-cascade", "tibet-tail", "tibet-trail", "tibet-ping", "tibet-pol"],
        "install": 'pip install "tibet[observability]"',
    },
    "ai-governance": {
        "desc": "AI governance, trust controls, airlock and bounded authority",
        "packages": ["tibet-airlock", "tibet-triage", "tibet-claw", "tibet-cortex", "tibet-sam"],
        "install": 'pip install "tibet[ai-governance]"',
    },
    "firewall": {
        "desc": "Semantic firewall and active security boundary",
        "packages": ["snaft", "tibet-snaft", "inject-bender"],
        "install": 'pip install "tibet[firewall]"',
    },
    "security": {
        "desc": "Governance controls + firewall + boundary gateways",
        "packages": [
            "tibet-airlock",
            "tibet-triage",
            "tibet-claw",
            "tibet-cortex",
            "tibet-sam",
            "snaft",
            "tibet-snaft",
            "inject-bender",
            "tibet-pqc",
            "tibet-gateway",
        ],
        "install": 'pip install "tibet[security]"',
    },
    "evidence": {
        "desc": "Evidence, audit, dossier, replay and bills of material",
        "packages": [
            "tibet-audit",
            "tibet-sbom",
            "tibet-cbom",
            "tibet-ai-sbom",
            "tibet-report",
            "tibet-wayback",
            "tibet-trail",
        ],
        "install": 'pip install "tibet[evidence]"',
    },
    "compliance": {
        "desc": "Compliance domains and operational assurance frameworks",
        "packages": ["tibet-nis2", "tibet-ci", "tibet-soc", "tibet-workload"],
        "install": 'pip install "tibet[compliance]"',
    },
    "agent": {
        "desc": "AInternet, I-Poll, MCP surfaces and session resume",
        "packages": [
            "ainternet",
            "ipoll",
            "tibet-ainternet-mcp",
            "tibet-ipoll-mcp",
            "tibet-phantom",
            "tibet-phantom-mcp",
            "tibet-context",
        ],
        "install": 'pip install "tibet[agent]"',
    },
    "conformance": {
        "desc": "Standards, contract vectors and MCP conformance helpers",
        "packages": ["tibet-conformance-vectors", "tibet-triage-mcp", "tibet-pol-mcp"],
        "install": 'pip install "tibet[conformance]"',
    },
    "interop": {
        "desc": "Optional enterprise interop and edge-specific adapters",
        "packages": ["tibet-spiffe", "tibet-edge"],
        "install": 'pip install "tibet[interop]"',
    },
    "tooling": {
        "desc": "Marketplace/tooling engine, not part of supported full installs",
        "packages": ["tibet-tools", "tibet-marketplace"],
        "install": 'pip install "tibet[tooling]"',
    },
    "lab": {
        "desc": "Everything for research and internal lab use, including niche adapters",
        "packages": [
            "tibet-core",
            "jis-core",
            "tibet-genesis",
            "tibet-timevector",
            "tibet-continuityd",
            "tibet-cap-bus",
            "tibet-cbom",
            "tibet-trail",
            "tibet-wayback",
            "tibet-phantom",
            "tibet-phantom-mcp",
            "tibet-ping",
            "tibet-overlay",
            "tibet-mux",
            "tibet-nc",
            "tibet-mesh",
            "tibet-zip",
            "tibet-pol",
            "tibet-tail",
            "tibet-cascade",
            "tibet-cmail",
            "tibet-keychain",
            "tibet-home-agent",
            "tibet-airlock",
            "tibet-triage",
            "tibet-claw",
            "tibet-cortex",
            "tibet-sam",
            "snaft",
            "tibet-snaft",
            "inject-bender",
            "tibet-pqc",
            "tibet-gateway",
            "tibet-audit",
            "tibet-sbom",
            "tibet-ai-sbom",
            "tibet-report",
            "tibet-nis2",
            "tibet-ci",
            "tibet-soc",
            "tibet-workload",
            "ainternet",
            "ipoll",
            "tibet-ainternet-mcp",
            "tibet-ipoll-mcp",
            "tibet-context",
            "tibet-conformance-vectors",
            "tibet-triage-mcp",
            "tibet-pol-mcp",
            "tibet-chip",
            "tibet-forge",
            "tibet-vault",
            "tibet-tools",
            "tibet-marketplace",
            "tibet-cobol",
            "tibet-anticheat",
            "tibet-y2k38",
            "tibet-iot",
            "tibet-edge",
            "tibet-spiffe",
            "tibet-router",
            "tibet-snap",
        ],
        "install": 'pip install "tibet[lab]"',
    },
    "legacy": {
        "desc": "Compatibility packages kept out of full installs",
        "packages": ["tibet-snap", "tibet-cobol", "tibet-y2k38", "tibet-anticheat", "tibet-router", "tibet-iot"],
        "install": 'pip install "tibet[legacy]"',
    },
    # Backwards-compatible aliases for earlier install docs.
    "core": {
        "desc": "Alias for zero-state",
        "packages": ["tibet-core", "jis-core", "tibet-genesis", "tibet-timevector"],
        "install": 'pip install "tibet[core]"',
    },
    "daemon": {
        "desc": "Alias for continuity",
        "packages": [
            "tibet-continuityd",
            "tibet-cap-bus",
            "tibet-cbom",
            "tibet-trail",
            "tibet-wayback",
            "tibet-phantom",
            "tibet-phantom-mcp",
        ],
        "install": 'pip install "tibet[daemon]"',
    },
    "agentic": {
        "desc": "Alias for agent",
        "packages": [
            "ainternet",
            "ipoll",
            "tibet-ainternet-mcp",
            "tibet-ipoll-mcp",
            "tibet-phantom",
            "tibet-phantom-mcp",
            "tibet-context",
        ],
        "install": 'pip install "tibet[agentic]"',
    },
    "safety": {
        "desc": "Alias for security",
        "packages": [
            "tibet-airlock",
            "tibet-triage",
            "tibet-claw",
            "tibet-cortex",
            "tibet-sam",
            "snaft",
            "tibet-snaft",
            "inject-bender",
            "tibet-pqc",
            "tibet-gateway",
        ],
        "install": 'pip install "tibet[safety]"',
    },
}

FULL_BUNDLE_NAMES = [
    "zero-state",
    "continuity",
    "network",
    "operator",
    "observability",
    "security",
    "evidence",
    "compliance",
    "agent",
    "conformance",
]

FULL_PACKAGES = []
for bundle_name in FULL_BUNDLE_NAMES:
    for package_name in BUNDLES[bundle_name]["packages"]:
        if package_name not in FULL_PACKAGES:
            FULL_PACKAGES.append(package_name)


def specs_for(package_names):
    """Return dependency specifiers for package names in order."""
    return [PACKAGE_SPECS[name] for name in package_names]
